### ISSUE TITLE
请问，你可以公开你训练的权重吗？

### ISSUE THREAD

**Issue by mengxzh15** [YaN9-Y/D4#1]
请问，是否可以共享你训练的权重，以百度云或者谷歌drive的方式。这样可以为研究者大大减少环境配置时间。谢谢。

**Comment by YaN9-Y** [comment]
之前已经公布了预训练权重，在首页getting started 的testing部分。如果有其他问题请联系我:)

**Comment by mengxzh15** [comment]
作者，感谢你的回复。我有三个问题，请问是否可以公开一个在真实数据上（如Fattal上的数据）的test_real.py文件或者一个具体的测试方式，我昨晚测了一下这种有标注数据的。但是，想测试一下真实数据的，却一直报错。其二，给出的代码中并没有requirements.txt这个文件。我没有安装kornia，所以将其使用的中值滤波那块注释掉了，我发现在室外数据上影响不大。其三，我在测试室内数据时，其PSNR只有19点多，这是什么情况呢？

**Comment by YaN9-Y** [comment]
mengxzh15你好，感谢你提出的问题。
1.关于测试代码，可以通过修改src/dataset.py和src/D4.py中的test部分进行单图像测试。
2.中值滤波是因为在训练sample过程中可视化时少部分极值影响了正常观看，去掉不影响训练测试效果。
3.配置文件已经更新，经测试在SOTS-indoor上PSNR为25.42，请使用test_example下的配置文件。
