### ISSUE TITLE
 some question about real-world hazy images checkpoint

### ISSUE THREAD

**Issue by YuZheng9** [YaN9-Y/D4#11]
Hello author, thank you very much for your work！

I want to use the checkpoint you mentioned in your paper for real world images(such as Fattal’s dataset or URHI ).

Could you please provide the download link?

Thanks!

**Comment by YaN9-Y** [comment]
I'm sorry that we didn't retain that checkpoint. However, you could use the provided checkpoint that is trained on SOTS-indoor, it shows acceptable performance on real-world images.
