### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by wowwowya** [YaN9-Y/D4#14]
when i run test.py ,there was a mistake which is 'Model' object has no attribute 'name',could you please tell me how to deal with it?

**Comment by wowwowya** [comment]
Author,Thanks for work a lot and your generous ,I'm high school student ,when I run "python3 test.py --model 1 --checkpoints ./checkpoints/quick_test",there was no reaction,could you tell me what I can do to deal with it,thanks a lot!!!!!

**Comment by YaN9-Y** [comment]
I'm sorry that I'm not currently at the lab to run the program.  But it should be able to successfully run according to the guidance in the readme.  Maybe you could send the detailed error messages and I'll try to help you to check where goes wrong.

**Comment by wowwowya** [comment]
非常非常感谢您的回复，我按照您在readme中的提示在pycharm的terminal中分别运行了“python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist
python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist”“然后将grooundtruth图像以及生成的文件路径都放入了config文件夹中，接着将预训练的权重复制在chekpoints的quick_test文件夹中，然后在terminal中将”python3 test.py --model 1 --checkpoints ./checkpoints/quick_test“复制上去，但是并没有任何反应，也没有result文件，请问您能帮我看看还有哪里的操作不正确吗？非常非常感谢！！！！

**Comment by wowwowya** [comment]
因为直接在terminal中粘贴那段命令没有反应，我就直接运行test.py,结果有这样的报错”
Traceback (most recent call last):
  File "E:\UID代码\D4-main\test.py", line 2, in <module>
    main(mode=2)
  File "E:\UID代码\D4-main\main.py", line 48, in main
    model = D4(config)
            ^^^^^^^^^^
  File "E:\UID代码\D4-main\src\D4.py", line 21, in __init__
    self.model = Model(config).to(config.DEVICE)
                 ^^^^^^^^^^^^^
  File "E:\UID代码\D4-main\src\models.py", line 43, in __init__
    super(Model, self).__init__(config)
  File "E:\UID代码\D4-main\src\models.py", line 26, in __init__
    self.gen_optimizer_path = os.path.join(config.PATH, 'optimizer_'+self.name + '.pth')
                                                                     ^^^^^^^^^
  File "D:\AAnaconda\envs\pytorch2\Lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Model' object has no attribute 'name'

Process finished with exit code 1
“您知道我哪里没有做对吗？非常非常非常非常感谢！！！

**Comment by YaN9-Y** [comment]
> 非常非常感谢您的回复，我按照您在readme中的提示在pycharm的terminal中分别运行了“python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist”“然后将grooundtruth图像以及生成的文件路径都放入了config文件夹中，接着将预训练的权重复制在chekpoints的quick_test文件夹中，然后在terminal中将”python3 test.py --model 1 --checkpoints ./checkpoints/quick_test“复制上去，但是并没有任何反应，也没有result文件，请问您能帮我看看还有哪里的操作不正确吗？非常非常感谢！！！！


没有反应这种情况没有遇到过，是完全没有输出程序直接结束还是程序卡住了呢？控制台有其他输出信息吗？

**Comment by wowwowya** [comment]
控制台没有任何反应，什么也没有输出也没有卡住就像这样


PS E:\UID代码\D4-main&gt; python3 test.py --model 1 --checkpoints ./checkpoints/quick_test
PS E:\UID代码\D4-main&gt; python3 test.py --model 1 --checkpoints ./checkpoints/quick_test
PS E:\UID代码\D4-main&gt;&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YaN9-Y/D4"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月3日(星期四) 晚上10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YaN9-Y/D4] test.py (Issue #14)





  
非常非常感谢您的回复，我按照您在readme中的提示在pycharm的terminal中分别运行了“python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist”“然后将grooundtruth图像以及生成的文件路径都放入了config文件夹中，接着将预训练的权重复制在chekpoints的quick_test文件夹中，然后在terminal中将”python3 test.py --model 1 --checkpoints ./checkpoints/quick_test“复制上去，但是并没有任何反应，也没有result文件，请问您能帮我看看还有哪里的操作不正确吗？非常非常感谢！！！！
  
没有反应这种情况没有遇到过，是完全没有输出程序直接结束还是程序卡住了呢？控制台有其他输出信息吗？

**Comment by YaN9-Y** [comment]
> 控制台没有任何反应，什么也没有输出也没有卡住就像这样 PS E:\UID代码\D4-main&gt; python3 test.py --model 1 --checkpoints ./checkpoints/quick_test PS E:\UID代码\D4-main&gt; python3 test.py --model 1 --checkpoints ./checkpoints/quick_test PS E:\UID代码\D4-main&gt;&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YaN9-Y/D4" ***@***.***&gt;; 发送时间:&nbsp;2023年8月3日(星期四) 晚上10:27 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [YaN9-Y/D4] test.py (Issue #14) 非常非常感谢您的回复，我按照您在readme中的提示在pycharm的terminal中分别运行了“python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist”“然后将grooundtruth图像以及生成的文件路径都放入了config文件夹中，接着将预训练的权重复制在chekpoints的quick_test文件夹中，然后在terminal中将”python3 test.py --model 1 --checkpoints ./checkpoints/quick_test“复制上去，但是并没有任何反应，也没有result文件，请问您能帮我看看还有哪里的操作不正确吗？非常非常感谢！！！！ 没有反应这种情况没有遇到过，是完全没有输出程序直接结束还是程序卡住了呢？控制台有其他输出信息吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

抱歉我没有在windows平台下进行过测试，如果可能的话可以尝试在ubuntu系统下进行运行。

**Comment by wowwowya** [comment]
我试试，谢谢您






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 晚上10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YaN9-Y/D4] test.py (Issue #14)





  
控制台没有任何反应，什么也没有输出也没有卡住就像这样 PS E:\UID代码\D4-main&gt; python3 test.py --model 1 --checkpoints ./checkpoints/quick_test PS E:\UID代码\D4-main&gt; python3 test.py --model 1 --checkpoints ./checkpoints/quick_test PS E:\UID代码\D4-main&gt;&nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YaN9-Y/D4" @.&gt;; 发送时间:&nbsp;2023年8月3日(星期四) 晚上10:27 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [YaN9-Y/D4] test.py (Issue #14) 非常非常感谢您的回复，我按照您在readme中的提示在pycharm的terminal中分别运行了“python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist”“然后将grooundtruth图像以及生成的文件路径都放入了config文件夹中，接着将预训练的权重复制在chekpoints的quick_test文件夹中，然后在terminal中将”python3 test.py --model 1 --checkpoints ./checkpoints/quick_test“复制上去，但是并没有任何反应，也没有result文件，请问您能帮我看看还有哪里的操作不正确吗？非常非常感谢！！！！ 没有反应这种情况没有遇到过，是完全没有输出程序直接结束还是程序卡住了呢？控制台有其他输出信息吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
抱歉我没有在windows平台下进行过测试，如果可能的话可以尝试在ubuntu系统下进行运行。

**Comment by YaN9-Y** [comment]
> 非常非常感谢您的回复，我按照您在readme中的提示在pycharm的terminal中分别运行了“python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist”“然后将grooundtruth图像以及生成的文件路径都放入了config文件夹中，接着将预训练的权重复制在chekpoints的quick_test文件夹中，然后在terminal中将”python3 test.py --model 1 --checkpoints ./checkpoints/quick_test“复制上去，但是并没有任何反应，也没有result文件，请问您能帮我看看还有哪里的操作不正确吗？非常非常感谢！！！！

另外请注意 “python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist
python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist” 这些命令中--path后边的路径需要替换为你自己数据的实际路径。 你也可以在重新下载本程序并复制权重文件后不运行其他命令直接运行 python3 test.py --model 1 --checkpoints ./checkpoints/quick_test 。 quick_test有已经配置好的数据文件用于直接测试。

**Comment by wowwowya** [comment]
太感谢您了！！您真是个大好人！！祝您天天开心！！！！！！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 晚上10:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YaN9-Y/D4] test.py (Issue #14)





  
非常非常感谢您的回复，我按照您在readme中的提示在pycharm的terminal中分别运行了“python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist”“然后将grooundtruth图像以及生成的文件路径都放入了config文件夹中，接着将预训练的权重复制在chekpoints的quick_test文件夹中，然后在terminal中将”python3 test.py --model 1 --checkpoints ./checkpoints/quick_test“复制上去，但是并没有任何反应，也没有result文件，请问您能帮我看看还有哪里的操作不正确吗？非常非常感谢！！！！
  
另外请注意 “python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist
 python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist” 这些命令中--path后边的路径需要替换为你自己数据的实际路径。 你也可以在重新下载本程序并复制权重文件后不运行其他命令直接运行 python3 test.py --model 1 --checkpoints ./checkpoints/quick_test 。 quick_test有已经配置好的数据文件用于直接测试。

**Comment by YaN9-Y** [comment]
> 太感谢您了！！您真是个大好人！！祝您天天开心！！！！！！！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年8月3日(星期四) 晚上10:53 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [YaN9-Y/D4] test.py (Issue #14) 非常非常感谢您的回复，我按照您在readme中的提示在pycharm的terminal中分别运行了“python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist”“然后将grooundtruth图像以及生成的文件路径都放入了config文件夹中，接着将预训练的权重复制在chekpoints的quick_test文件夹中，然后在terminal中将”python3 test.py --model 1 --checkpoints ./checkpoints/quick_test“复制上去，但是并没有任何反应，也没有result文件，请问您能帮我看看还有哪里的操作不正确吗？非常非常感谢！！！！ 另外请注意 “python scripts/flist.py --path path_to_SOTS_indoor_hazy_path --output ./datasets/sots_test_hazy_indoor.flist”“python scripts/flist.py --path ITS_train_hazy_path --output ./datasets/its_train_hazy.flist python scripts/flist.py --path ITS_train_gt_path --output ./datasets/its_train_gt.flist” 这些命令中--path后边的路径需要替换为你自己数据的实际路径。 你也可以在重新下载本程序并复制权重文件后不运行其他命令直接运行 python3 test.py --model 1 --checkpoints ./checkpoints/quick_test 。 quick_test有已经配置好的数据文件用于直接测试。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不客气，祝一切顺利！
