### ISSUE TITLE
关于SOTS-outdoor数据集psnr与ssim

### ISSUE THREAD

**Issue by diadestiny** [YaN9-Y/D4#15]
您好，感谢您的工作！
请问您会议论文table1的SOTS-outdoor数据集psnr与ssim是用您公布的weights（只在ITS上训练）来计算得到的吗，我用您公布的权值，只能复现左边SOTS-indoor的psnr与ssim，但是无法复现outdoor的psnr与ssim。
![image](https://github.com/YaN9-Y/D4/assets/44188454/c54fec00-9b15-4c99-b202-491c1ce7d65b)
您论文table1的意思应该是都是用ITS训，然后在不同测试集测试，想请问下如何复现outdoor数据集结果呢？
我计算得到的outdoor的psnr与ssim如下（基于您公布的权值）：
![image](https://github.com/YaN9-Y/D4/assets/44188454/a7c00cac-d09a-4899-a4d4-a1462153a3f6)

**Comment by YaN9-Y** [comment]
请在测试时将config.yml中的DATASET项设为SOTS-outdoor
