### ISSUE TITLE
训练的问题

### ISSUE THREAD

**Issue by syy-whu** [YaN9-Y/D4#2]
请问我没有改任何配置再训练时候出现nan的现象，目测是由depth那个loss函数造成的？
![f0c0c45c4bd0e306b83e7d5823933be](https://user-images.githubusercontent.com/86900290/175235988-243e39e2-3d79-4784-9151-f70c1a212e70.png)

**Comment by YaN9-Y** [comment]
感谢指出问题，我已经更新了可能出现问题位置的代码，如果还存在问题请联系我。
