### ISSUE TITLE
epoch？ 1500000？

### ISSUE THREAD

**Issue by ghost** [YaN9-Y/D4#3]
![1658401901437](https://user-images.githubusercontent.com/58910346/180200431-23a517bf-a2f1-4531-99cb-db26177a4f48.png)

**Comment by YaN9-Y** [comment]
Thanks for your interest, MAX_ITERS means the number of max iterations, not the max epochs.

**Comment by ghost** [comment]
> Thanks for your interest, MAX_ITERS means the number of max iterations, not the max epochs.

![1658411733649](https://user-images.githubusercontent.com/58910346/180231410-67a1a366-dd99-4d05-b5a2-81559799fa6e.png)
![1658411759594](https://user-images.githubusercontent.com/58910346/180231440-f6c4bc6a-2485-4b96-a9d5-c5f429b87163.png)
There is a bug here.

**Comment by ghost** [comment]
Can your framework be trained on unpaired data mode? （i.e., the hazy image and clean image are unpaired.）
