### ISSUE TITLE
self.model.save(save_best,psnr,iteration) TypeError: save() takes 1 positional argument but 4 were given

### ISSUE THREAD

**Issue by 1094558673** [YaN9-Y/D4#5]
Sorry to bother you, but I'm having some problems with the model run:

Traceback (most recent call last):
  File "train.py", line 2, in <module>
    main(mode=1)
  File "/media/cui/文件/CJ6/D4-main/main.py", line 56, in main
    model.train()
  File "/media/cui/文件/CJ6/D4-main/src/D4.py", line 141, in train
    self.save()
  File "/media/cui/文件/CJ6/D4-main/src/D4.py", line 58, in save
    self.model.save(save_best,psnr,iteration)
TypeError: save() takes 1 positional argument but 4 were given

It seems that the save_best, PSNR, and iteration parameters of the save function in D4.py are not used. My understanding here is to save the PTH file many times? I want to ask if it makes any difference if it is deleted or if it should be corrected;
I will be very grateful if you can reply me!

**Comment by YaN9-Y** [comment]
Thanks for your issue, I have removed the mistakenly used parameters and the problem should be fixed.  If there still exists any problem please feel free to contact me.
