### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hocking-cloud** [YaN9-Y/D4#7]
When we change the test data set, it always prompts the following error message: 
urllib.error.URLError: <urlopen error [Errno 110] Connection time out>

![图片](https://user-images.githubusercontent.com/55275107/193580426-5b5ff1bf-369b-4688-b81f-a50c4de797f6.png)

Ask for an answer, thanks!

**Comment by mengxzh15** [comment]
需要更改后的测试代码吗？我有哦。我问作者，作者不想改。我给他改了一版。可以直接用。

**Comment by YaN9-Y** [comment]
Hi, hocking-cloud.
The Connection time-out problem could be solved by using a global VPN.

**Comment by hocking-cloud** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    需要哦，能不能打包发给我，非常感谢啊！
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/10/2022 10:14
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [YaN9-Y/D4] Help (Issue #7)
        
      
    
  
  

需要更改后的测试代码吗？我有哦。我问作者，作者不想改。我给他改了一版。可以直接用。

**Comment by hocking-cloud** [comment]
> 需要更改后的测试代码吗？我有哦。我问作者，作者不想改。我给他改了一版。可以直接用。

需要哦，能不能打包发给我，非常感谢啊！ it_hero@126.com

**Comment by p123123168** [comment]
> 需要更改后的测试代码吗？我有哦。我问作者，作者不想改。我给他改了一版。可以直接用。

你好，可以给我一份吗？谢谢！邮箱：394729624@qq.com

**Comment by lishaoji91** [comment]
> 需要更改后的测试代码吗？我有哦。我问作者，作者不想改。我给他改了一版。可以直接用。

你好，请问能不能给我发一份呢？万分感谢！1261366510@qq.com

**Comment by hocking-cloud** [comment]
没收到哦  作者没发给我
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        4/6/2023 16:58
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [YaN9-Y/D4] Help (Issue #7)
        
      
    
  


需要更改后的测试代码吗？我有哦。我问作者，作者不想改。我给他改了一版。可以直接用。

***@***.***

**Comment by mengxzh15** [comment]
其实很简单的，只需要把不必要的代码删除，更改一下路径就好了

**Comment by tongchangD** [comment]
> 其实很简单的，只需要把不必要的代码删掉，改一下路径就好了

哈哈哈，感觉回邮件地址的都收到了部分疑惑

**Comment by andwizard** [comment]
> 其实很简单的，只需要把不必要的代码删除，更改一下路径就好了

大佬可以教一下改哪些嘛，我看报错看不出来要改哪里

**Comment by andwizard** [comment]
> 其实很简单的，只需要把不必要的代码删除，更改一下路径就好了

大佬可以教一下改哪些嘛，我看报错看不出来要改哪里
