### ISSUE TITLE
How to test and calculate the meteic of the dehazed images such as on sots indoor dataset?

### ISSUE THREAD

**Issue by syzlhh** [YaN9-Y/D4#9]
Thanks for your good work and the release of the codes. I have a question when I test the demo code. The PSNR and SSIM metrics test on SOTS indoor with the pretrained model provided big gap with the record in the paper?  The online PSNR is just around 20db.
Can you provide the metric calculate codes or provide some instructions?
Thanks a lot!

**Comment by YaN9-Y** [comment]
Hi syzlhh,
The DATASET term in the config file needs to be correctly filled.  You can try to use the config file under checkpoints/test_example for testing.

**Comment by 123456789-qwer** [comment]
> Hi syzlhh, The DATASET term in the config file needs to be correctly filled. You can try to use the config file under checkpoints/test_example for testing.

I have met the same problem, how should I solve it? Thanks!

**Comment by 123456789-qwer** [comment]
The PSNR and SSIM metrics test on SOTS indoor with the pretrained model provided big gap with the record in the paper
